### ISSUE TITLE
Composite primary keys fail in index.sql

### ISSUE THREAD

**Issue by gerbal** [alvare/discogs2pg#1]
The composite primary keys on indexes.sql are not unique and are not reliable not-null.

**Comment by clrnd** [comment]
Could you please elaborate?
1. Are you seeing them fail on specific data?
2. What does "not reliable not-null" mean?
3. What kind of solution would you suggest? (automatic serial?)

Thanks!

**Comment by RobSis** [comment]
Hello. I had the same issue back when I was indexing. (don't remember the exact error message, though).

I remember I had to remove all duplicate rows from all intermediate tables to make indexing possible.

EDIT: the error message was *something like* 
`SQL error: ERROR: could not create unique index "master_artist" DETAIL: Key (master_id)=() is duplicated`

**Comment by clrnd** [comment]
Hey! This was a bug and I fixed it a time ago.

**Comment by z-yan** [comment]
Hello. I have a similar issue with index creation: `ALTER TABLE
ERROR:  could not create unique index "master_artist_pkey"
DETAIL:  Key (master_id, artist_id)=(59474, 1355202) is duplicated.
`

**Comment by clrnd** [comment]
Hi, this is a different thing though. But let me see, you can always drop the unique constraint and have the performance improvement of the index anyway.

**Comment by clrnd** [comment]
So yeah indexes were quite broken 😂 I'll be doing a release soon.
