### ISSUE TITLE
Table release not found barcode collumn

### ISSUE THREAD

**Issue by addodelgrossi** [alvare/discogs2pg#2]
In the table release there is no column barcode, any reason ?

**Comment by clrnd** [comment]
I must have left it out accidentally :tongue: 
Wanna add it yourself?

**Comment by addodelgrossi** [comment]
Sure ! Now !

**Comment by addodelgrossi** [comment]
Alvarez, implemented the adjustment, but in validation checked that made no sense because the information is already saved in release_identifier table.

Sorry, I will close the issue.
