### ISSUE TITLE
Release - Master mapping is missing

### ISSUE THREAD

**Issue by SimonTeixidor** [alvare/discogs2pg#4]
I imported the schema and ran `discogs2pg  -d 20180201`. This takes a while and fills up the database, but after it finishes none of the releases are mapped to a master:

```
simon=# select * from release where master_id is not null;
 id | status | title | country | released | notes | genres | styles | master_id | data_quality
----+--------+-------+---------+----------+-------+--------+--------+-----------+--------------
(0 rows)

simon=# select count(*) from release;
  count
---------
 9442718
(1 row)

simon=#
```

Am I doing something wrong? Perhaps something has changed in the exports from Discogs?

**Comment by clrnd** [comment]
🤔 let me check

**Comment by clrnd** [comment]
Yeah Discogs changed it's format slightly, but the parsing shouldn't break for this kind of things (the `<master_id>` tag now has an attribute `is_main_release` which I'll ignore for now).

In any case I fixed it and also added gzip functionality so it can read the compressed files directly.

I'll release it later this week and also see if I can add some Linux and macOS binaries so people don't need to download terabytes of dependencies :rofl: .

Thanks for your feedback 👍

**Comment by SimonTeixidor** [comment]
Fantastic! I'll try it out right away. 👍
