### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by csteinlehner** [alvare/discogs2pg#6]
Hi,

I'm trying to import the latest dump (20180401) and getting following error while importing:

`discogs2pg: user error (Database.PostgreSQL.Simple.Copy.putCopyEnd: failed to parse command status
Connection error: ERROR:  value "999999999999" is out of range for type integer
CONTEXT:  COPY release_format, line 9856798, column qty: "999999999999"`

I don't really understand what it is happening, but is the latest dump too big?

**Comment by clrnd** [comment]
Interesting. It’s probably a data error but never mind, try changing the type of the release_format “qty” column in “tables.sql” from ‘integer’ to ‘bigint’ or maybe ‘text’ if that fails. The number is too big for the ‘integer’ type it seems.

**Comment by csteinlehner** [comment]
Thanks, that worked.
