### ISSUE TITLE
slow execution after running script on a new datadump

### ISSUE THREAD

**Issue by otosky** [alvare/discogs2pg#7]
Thanks for building this tool!  Its saved me a ton of time in gathering the migrating the Discogs Data for a pet project of mine.

I have a question about the intended usage of the package AFTER an initial data dump parse:  If I run the script on a batch of xml files from October and then run it again on the next set of files in November, is there an intermediate action I should take?

Not sure if it's due to the indices on the release-related tables, but I've been running the script on the newest data dump after having filled the tables with last months dump and I'm finding the COPYing process to be pretty slow.  Over 12 hours now and it still hasn't finished.

Am I better off just dropping the tables altogether and then refilling them with the new data?  That way it can just bulk copy?

**Comment by clrnd** [comment]
Hey! Now that you mention it, I never thought about doing incremental dumps.

What is probably happening now is that it's loading everything twice, that's why it is so slow (the tables where you are dumping are already gigantic!).

For now I'd recommend you drop everything before. Not the nicest solution but will do for now.

In the future I may think about adding support for "updating" a dump.

Cheers 🙌

**Comment by otosky** [comment]
Yeah that extra functionality would be dope!  I've never written anything in Haskell, but I might try my hand at it and send you a pull request.  

For my purposes, I still need to be able to read from those tables while the bulk-copy update is happening, so I'm thinking to:
- have the script bulk copy to temp tables
- build the indexes
- drop the old tables and ALTER TABLE to rename the temp tables to the original names

Still not incremental, but allows the built tables to continue to be read from while the new ones are being copied in.

**Comment by clrnd** [comment]
Oh yeah sure, any DB trick will work there.

**Comment by justinkraus** [comment]
> For now I'd recommend you drop everything before. Not the nicest solution but will do for now.

This worked for me!
